const teams = {
	'00'  : 'invalid',
	'10' : 'real madrid', 
	'11' : 'barcelona',
	'12' : 'atletico madrid',
	'13' : 'valencia',
	'14' : 'athletic bilbao',
	'15' : 'sevilla',
	'16' : 'espanyol',
	'17' : 'sociedad',
	'19' : 'zaragoza',
	'20' : 'betis',
	'21' : 'celta',
	'22' : 'deportivo',
	'23' : 'valladolid',
	'24' : 'racing',
	'25' : 'sporting',
	'26' : 'osasuna',
	'27' : 'malaga',
	'28' : 'oviedo',
	'29' : 'mallorca',
	'30' : 'villarreal',
	'31' : 'palmas',
	'32' : 'vallecano',
	'33' : 'getafe',
	'34' : 'granada',
	'35' : 'elche',
	'36' : 'hercules',
	'37' : 'alaves',
	'38' : 'tenerife',
	'39' : 'levante',
	'40' : 'murcia',
	'41' : 'salamanca',
	'42' : 'sabadell',
	'43' : 'cadiz',
	'44' : 'logrones',
	'45' : 'castellon',
	'46' : 'albacete',
	'47' : 'almeria',
	'48' : 'eibar',
	'49' : 'cordoba',
	'50' : 'compostela',
	'51' : 'recreativo',
	'52' : 'burgos',
	'53' : 'pontevedra',
	'54' : 'numancia',
	'55' : 'leganes',
	'56' : 'arenas',
	'57' : 'burgos',
	'58' : 'gimnastic',
	'59' : 'girona',
	'60' : 'extremadura',
	'61' : 'merida',
	'62' : 'alcoyano',
	'63' : 'jaen',
	'64' : 'union',
	'65' : 'ad almeria',
	'66' : 'europa',
	'67' : 'lleida',
	'68' : 'xerez',
	'69' : 'huesca',
	'70' : 'condal',
	'71' : 'tetuan',
	'72' : 'leonesa'
}

module.exports = teams;