const teams = {
	'00'  : 'invalid',
	'10' : 'arsenal',
	'11' : 'aston',
	'12' : 'barnsley',
	'13' : 'birmingham',
	'14' : 'blackburn',
	'15' : 'blackpool',
	'16' : 'bolton',
	'17' : 'bournemouth',
	'18' : 'bradford',
	'19' : 'brighton',
	'20' : 'burnley',
	'21' : 'cardiff',
	'22' : 'charlton',
	'23' : 'chelsea',
	'24' : 'coventry',
	'25' : 'crystal',
	'26' : 'derby',
	'27' : 'everton',
	'27' : 'e-erton',
	'28' : 'fulham',
	'29' : 'huddersfield',
	'30' : 'hull',
	'31' : 'ipswich',
	'32' : 'leed',
	'33' : 'leicester',
	'34' : 'liverpool',
	'34' : 'Li-erpool',
	'35' : 'manchester city',
	'35' : 'man city',
	'35' : 'Man. City',
	'36' : 'manchester utd',
	'36' : 'man utd',
	'37' : 'middlesbrough',
	'38' : 'newcastle',
	'39' : 'norwich',
	'40' : 'nottingham',
	'41' : 'oldham',
	'42' : 'portsmouth',
	'43' : 'queens',
	'44' : 'reading',
	'45' : 'sheffield united',
	'45' : 'sheffield',
	'45' : 'sheffield utd',
	'46' : 'sheffield wednesday',
	'47' : 'southampton',
	'48' : 'stoke',
	'49' : 'sunderland',
	'50' : 'swansea',
	'51' : 'swindon',
	'52' : 'tottenham',
	'53' : 'watford',
	'54' : 'bromwich',
	'55' : 'west ham',
	'56' : 'wigan',
	'57' : 'wimbledon',
	'58' : 'wolverhampton',
	'58' : 'wol-erhampton',
	'59' : 'hampton'
}

module.exports = teams;